const express = require("express")
const userAuthRouter = require("../routes/auth_users")
const userRouter = require("../routes/users")
const instructorAuthRouter = require("../routes/auth_instructors")
const instructorRouter = require("../routes/instructors")
const instructorCommentRouter = require("../routes/instructor_comments")
const photoRouter = require("../routes/photos")
const courseRouter = require("../routes/courses")
const adminRouter = require("../routes/admins")
const adminAuthRouter = require("../routes/auth_admins")
const categoryRouter = require("../routes/categories")
const useError = require("../middleware/useError")

module.exports = function(app){
    app.use(express.json())
    app.use(express.urlencoded({extended:true}))

    app.use("/api/auth/user",userAuthRouter)
    app.use("/api/users",userRouter)
    app.use("/api/auth/instructor",instructorAuthRouter)
    app.use("/api/instructors",instructorRouter)
    app.use("/api/instructors/comments",instructorCommentRouter)
    app.use("/api/photos",photoRouter)
    app.use("/api/courses",courseRouter)
    app.use("/api/admins",adminRouter)
    app.use("/api/auth/admin",adminAuthRouter)
    app.use("/api/categories",categoryRouter)
    app.use(useError)
}